### ISSUE TITLE
Why set the env 'TERM=xterm'

### ISSUE THREAD

**Issue by chenjunnn** [deluan/zsh-in-docker#13]
I am using vscode built-in terminal, and when I use this script to create a container, I found the zsh-auto-suggestion is not working properly as the color of the suggestion is wrong:
- Expected: 
![image](https://user-images.githubusercontent.com/57067221/155968347-3061ba30-82e8-4d09-aa5b-d93c022d499c.png)

- Actually:
![image](https://user-images.githubusercontent.com/57067221/155968306-e114c291-8b3c-4174-8f80-3dbf2be311a2.png)

Then I found it was caused by the env `TERM` was set to `xterm`.
So I remove the `export TERM=xterm`, then `echo $TERM` to find that it is `xterm-256color` originally. 
I wonder why the env 'TERM=xterm' would be set and if there should be an option to disable it.

**Comment by deluan** [comment]
I will do more tests and make sure `xterm-256color` is available in all distros supported before changing this. Thanks for reporting.

**Comment by petertheprocess** [comment]
Hi, maybe we can check if this varible has been set, if not set it to xterm.
```
if [ -z "$TERM" ]; then
  export TERM="xterm"
fi
```
Then we can pass this env varible during lauching like this
```
docker run -it --env=TERM=xterm-256color image:tag zsh
```

**Comment by deluan** [comment]
The PR #30 should allow the TERM setting to be bypassed.
