### ISSUE TITLE
How do I exec into the container using zsh?

### ISSUE THREAD

**Issue by simplenotezy** [deluan/zsh-in-docker#15]
I've installed the package, but when trying to exec into it I get:

    OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "zsh": executable file not found in $PATH: unknown

Using:

    docker exec -it 6ea4953e2df4 sh

**Comment by LanzaTyler** [comment]
@simplenotezy You just want to replace `sh` with `zsh`.
In your case:
`docker exec -it 6ea4953e2df4 zsh`

If using docker-compose: 
`docker-compose exec app zsh`

**Comment by simplenotezy** [comment]
Duh - what a brain fart. Anyways, thanks!
