### ISSUE TITLE
Error trying to build image with default options

### ISSUE THREAD

**Issue by erlloyd** [deluan/zsh-in-docker#5]
I noticed today when I try to install this in a docker container, I'm getting the following error:

`sh: 105: printf: usage: printf format [arg ...]`

This is on a "buster" based image, if that matters

**Comment by deluan** [comment]
Sorry, my bad. Should be fixed in dad4ec1. I'm releasing a fix now.

By the way, I'm now versioning the script and the correct way to use it now is to wget it from `https://github.com/deluan/zsh-in-docker/releases/download/v${VERSION}/zsh-in-docker.sh` instead of from master

**Comment by deluan** [comment]
Just released v1.0.2 with the fix.
